# Generated by Django 4.2.3 on 2023-07-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(blank=True, max_length=50, null=True)),
                ("id_padre", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "items",
                "managed": False,
            },
        ),
    ]
